"""initial migration

Revision ID: 82825ca3aba7
Revises: 
Create Date: 2024-07-25 13:10:42.101283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82825ca3aba7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'friends', ['friendship_id'])
    op.create_unique_constraint(None, 'games', ['game_id'])
    op.create_unique_constraint(None, 'lookingforgame', ['looking_id'])
    op.create_unique_constraint(None, 'moves', ['move_id'])
    op.create_unique_constraint(None, 'profile', ['profile_id'])
    op.create_unique_constraint(None, 'role_logs', ['log_id'])
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_unique_constraint(None, 'roomstoring', ['room_id'])
    op.create_unique_constraint(None, 'tournament_registrations', ['registration_id'])
    op.create_unique_constraint(None, 'tournaments', ['tournament_id'])
    op.create_unique_constraint(None, 'user_settings', ['user_setting_id'])
    op.create_unique_constraint(None, 'user_statistics', ['user_statistics_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_statistics', type_='unique')
    op.drop_constraint(None, 'user_settings', type_='unique')
    op.drop_constraint(None, 'tournaments', type_='unique')
    op.drop_constraint(None, 'tournament_registrations', type_='unique')
    op.drop_constraint(None, 'roomstoring', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'role_logs', type_='unique')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_constraint(None, 'moves', type_='unique')
    op.drop_constraint(None, 'lookingforgame', type_='unique')
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_constraint(None, 'friends', type_='unique')
    # ### end Alembic commands ###
